### ISSUE TITLE
[Crashlytics] Cannot read property 'rowsHashmap' of null 

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1723]
**Crashlytics Link**
[link](https://console.firebase.google.com/u/0/project/plh-teens-app1/crashlytics/app/android:international.idems.plh_teens_tz/issues/fe90d040655e0f305fb2bff39c42b583?time=last-seven-days&sessionEventKey=63C670B700CB000122694D7F883CA756_1768003439610380539)

**Report txt**
```Non-fatal Exception: com.getcapacitor.community.firebasecrashlytics.JavaScriptException
Uncaught (in promise): TypeError: Cannot read property 'rowsHashmap' of null TypeError: Cannot read property 'rowsHashmap' of null 
at M.<anonymous> (http://localhost/main.9f0ed43a6f92a826.js:1:1422531) 
at Generator.next (<anonymous>) 
at st (http://localhost/main.9f0ed43a6f92a826.js:1:1875) 
at T.invoke (http://localhost/polyfills.c906600eb8317419.js:1:25216) 
at Object.onInvoke (http://localhost/main.9f0ed43a6f92a826.js:1:2452103) 
at T.invoke (http://localhost/polyfills.c906600eb8317419.js:1:25155) 
at T.run (http://localhost/polyfills.c906600eb8317419.js:1:20297) 
at http://localhost/polyfills.c906600eb8317419.js:1:36041 
at T.invokeTask (http://localhost/polyfills.c906600eb8317419.js:1:25900) 
at Object.onInvokeTask (http://localhost/main.9f0ed43a6f92a826.js:1:2451918)
```

This issue has 15 non-fatal events affecting 6 users

**Diagnosis (if known)**
_cause of error relating to codebase_

**Suggested fix (if known)**
_recommended means to fix_

**Comment by chrismclarke** [comment]
Likely an authoring issue (cannot find a specific datalist), however no easy way to tell which list it is. Will need follow-up to add better context to crash reports

**Comment by chrismclarke** [comment]
I think the error persists but wording changed perhaps? Likely same as #1870 so can discuss there instead
