### ISSUE TITLE
[Crashlytics] "TypeError: undefined is not iterable"

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#1867]
**Crashlytics Link**
https://app.glitchtip.com/idems/issues/1832174

**Report txt**
```js
Error:Uncaught (in promise): TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) at l.<anonymous> (https://plh-tz.web.app/main.bf3661cef...
 at l.<anonymous> (webpack:///./src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts:85:7)
 at Generator.next (<anonymous>)
 at Se (webpack:///./node_modules/tslib/tslib.es6.js:73:43)
 at C.invoke (webpack:///./node_modules/zone.js/dist/zone.js:409:30)
 at Object.onInvoke (webpack:///./node_modules/@angular/core/fesm2020/core.mjs:25620:33)
 at C.invoke (webpack:///./node_modules/zone.js/dist/zone.js:408:56)
 at C.run (webpack:///./node_modules/zone.js/dist/zone.js:169:47)
 at ? (webpack:///./node_modules/zone.js/dist/zone.js:1326:38)
 at C.invokeTask (webpack:///./node_modules/zone.js/dist/zone.js:443:35)
 at Object.onInvokeTask (webpack:///./node_modules/@angular/core/fesm2020/core.mjs:25607:33)
 at C.invokeTask (webpack:///./node_modules/zone.js/dist/zone.js:442:64)
 at C.runTask (webpack:///./node_modules/zone.js/dist/zone.js:214:51)
 at drainMicroTaskQueue (webpack:///./node_modules/zone.js/dist/zone.js:632:39)
 at C.invokeTask [as invoke] (webpack:///./node_modules/zone.js/dist/zone.js:529:25)
 at G (webpack:///./node_modules/zone.js/dist/zone.js:1727:22)
 at globalCallback (webpack:///./node_modules/zone.js/dist/zone.js:1758:31)
 at IDBTransaction.ue (webpack:///./node_modules/zone.js/dist/zone.js:1794:20)
 at resolvePromise (webpack:///./node_modules/zone.js/dist/zone.js:1262:35)
 at ? (webpack:///./node_modules/zone.js/dist/zone.js:1169:21)
 at ? (webpack:///./node_modules/zone.js/dist/zone.js:1185:37)
 at Se (webpack:///./node_modules/tslib/tslib.es6.js:73:86)
 at C.invoke (webpack:///./node_modules/zone.js/dist/zone.js:409:30)
 at Object.onInvoke (webpack:///./node_modules/@angular/core/fesm2020/core.mjs:25620:33)
 at C.invoke (webpack:///./node_modules/zone.js/dist/zone.js:408:56)
 at C.run (webpack:///./node_modules/zone.js/dist/zone.js:169:47)
 at ? (webpack:///./node_modules/zone.js/dist/zone.js:1326:38)
 at C.invokeTask (webpack:///./node_modules/zone.js/dist/zone.js:443:35)
 at Object.onInvokeTask (webpack:///./node_modules/@angular/core/fesm2020/core.mjs:25607:33)
 at C.invokeTask (webpack:///./node_modules/zone.js/dist/zone.js:442:64)
 at C.runTask (webpack:///./node_modules/zone.js/dist/zone.js:214:51)
 at drainMicroTaskQueue (webpack:///./node_modules/zone.js/dist/zone.js:632:39)
 at C.invokeTask [as invoke] (webpack:///./node_modules/zone.js/dist/zone.js:529:25)
 at G (webpack:///./node_modules/zone.js/dist/zone.js:1727:22)
 at globalCallback (webpack:///./node_modules/zone.js/dist/zone.js:1758:31)
 at IDBTransaction.ue (webpack:///./node_modules/zone.js/dist/zone.js:1794:20)
```

**Diagnosis (if known)**
Seems to be an issue with `task-progress-bar.component.ts`, specifically during the function call `this.taskService.evaluateHighlightedTaskGroup()`

**Comment by esmeetewinkel** [comment]
This looks like the same issue as [this Firebase issue](https://console.firebase.google.com/u/0/project/plh-teens-app1/crashlytics/app/android:international.idems.plh_teens_tz/issues/4bb85710fee29196b29a7df473793314?time=last-seven-days&sessionEventKey=64292118036400014E165AE399D3DBBD_1795782077586672313) affecting one user (24 times) which seems to use Apple (`Mozilla/5.0 (Linux; Android 11; itel A661W Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36`) so I'm guessing that's @jfmcquade

**Comment by esmeetewinkel** [comment]
https://app.glitchtip.com/idems/issues/1984139?project=2233

**Comment by jfmcquade** [comment]
Looking at the "breadcrumbs" on the issues linked to above, I can see that consistently the error is preceded by `[HIGHLIGHTED TASK GROUP] - No highlighted task group is set`, which indicates that all the tasks have been completed (i.e. the user has completed every task). This will happen the first time the user completes all the tasks, but also, due to the way the completion status is evaluated, every time that user returns to the homepage. This would explain why we see so many of these errors logged.

I have replicated the error running the `plh_tz` deployment in emulation, see video below.

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/fab28a1e-759b-4fed-934a-d14a6b5ee489

As this is an issue triggered by completing all task groups, it should have been fixed by #1676, but that seems to have introduced a different error. In any case, the issue should only affect users who have completed all modules and it doesn't cause any issues for the user as far as I can tell, so it is not as critical as it first appears. But it would still be good to fix of course, I am looking into it now.

Additionally, I noticed that these Glitchtip error logs do not contain a human readable stack trace, suggesting an issue with the source maps. It may be the case that this has been fixed by #1834, and is not reflected on Glitchtip because we haven't made a release since then? What do you think, @chrismclarke?
When running locally, I get a stack trace matching [this issue](https://app.glitchtip.com/idems/issues/1832174/events/73c90d212a664a458a3533cf6fd3c44d), but [this issue](https://app.glitchtip.com/idems/issues/1968154) and [this issue](https://app.glitchtip.com/idems/issues/1984139) do seem to be logging the same error, but without the first (helpful) line.
