### ISSUE TITLE
[Crashlytics] TypeError: Cannot read properties of null (reading 'rowsHashmap')

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1870]
**Crashlytics Link**
https://app.glitchtip.com/idems/issues/1873991?project=2233

**Report txt**
```
Error:Uncaught (in promise): TypeError: Cannot read properties of null (reading 'rowsHashmap') TypeError: Cannot read properties of null (reading 'rowsHashmap') at k.<anonymous> (http://localhost/main.1284971fb87f94b7.js:1:1164816) at Generator.nex...
 at k.<anonymous> (/main.1284971fb87f94b7.js:1:1164816)
 at Generator.next (<anonymous>)
 at Se (/main.1284971fb87f94b7.js:1:2552470)
 at C.invoke (/polyfills.e91c1101d08ae204.js:1:35355)
 at Object.onInvoke (/main.1284971fb87f94b7.js:1:2702673)
 at C.invoke (/polyfills.e91c1101d08ae204.js:1:35293)
 at C.run (/polyfills.e91c1101d08ae204.js:1:30377)
 at ? (/polyfills.e91c1101d08ae204.js:1:46351)
 at C.invokeTask (/polyfills.e91c1101d08ae204.js:1:36043)
 at Object.onInvokeTask (/main.1284971fb87f94b7.js:1:2702484)
 at C.invokeTask (/polyfills.e91c1101d08ae204.js:1:35963)
 at C.runTask (/polyfills.e91c1101d08ae204.js:1:31053)
 at ge (/polyfills.e91c1101d08ae204.js:1:38472)
 at C.invokeTask [as invoke] (/polyfills.e91c1101d08ae204.js:1:37221)
 at G (/polyfills.e91c1101d08ae204.js:1:50974)
 at se (/polyfills.e91c1101d08ae204.js:1:51264)
 at IDBTransaction.ue (/polyfills.e91c1101d08ae204.js:1:51549)
 at re (/polyfills.e91c1101d08ae204.js:1:45519)
 at ? (/polyfills.e91c1101d08ae204.js:1:44552)
 at ? (/polyfills.e91c1101d08ae204.js:1:44658)
 at Ve (/main.1284971fb87f94b7.js:1:2552544)
 at C.invoke (/polyfills.e91c1101d08ae204.js:1:35355)
 at Object.onInvoke (/main.1284971fb87f94b7.js:1:2702673)
 at C.invoke (/polyfills.e91c1101d08ae204.js:1:35293)
 at C.run (/polyfills.e91c1101d08ae204.js:1:30377)
 at ? (/polyfills.e91c1101d08ae204.js:1:46351)
 at C.invokeTask (/polyfills.e91c1101d08ae204.js:1:36043)
 at Object.onInvokeTask (/main.1284971fb87f94b7.js:1:2702484)
 at C.invokeTask (/polyfills.e91c1101d08ae204.js:1:35963)
 at C.runTask (/polyfills.e91c1101d08ae204.js:1:31053)
 at ge (/polyfills.e91c1101d08ae204.js:1:38472)
 at C.invokeTask [as invoke] (/polyfills.e91c1101d08ae204.js:1:37221)
 at G (/polyfills.e91c1101d08ae204.js:1:50974)
 at se (/polyfills.e91c1101d08ae204.js:1:51264)
 at IDBTransaction.ue (/polyfills.e91c1101d08ae204.js:1:51549)
```

**Comment by esmeetewinkel** [comment]
Also 
https://app.glitchtip.com/idems/issues/1832175
https://app.glitchtip.com/idems/issues/1865413
